-- Add demo volunteers to the profiles table
insert into public.profiles (
   id,
   name,
   phone,
   role,
   skills,
   age,
   updated_at
) values ( gen_random_uuid(),
           'Dhruval',
           '9913238001',
           'volunteer',
           array['Event Management','Communication'],
           25,
           now() ),( gen_random_uuid(),
                     'Amogh',
                     '9913238002',
                     'volunteer',
                     array['Technical Support','Photography'],
                     23,
                     now() ),( gen_random_uuid(),
                               'Nirlipta',
                               '9913238003',
                               'volunteer',
                               array['Coordination','First Aid'],
                               27,
                               now() ),( gen_random_uuid(),
                                         'Om',
                                         '9913238004',
                                         'volunteer',
                                         array['Transportation','Logistics'],
                                         24,
                                         now() ),( gen_random_uuid(),
                                                   'Kartik',
                                                   '9913238005',
                                                   'volunteer',
                                                   array['Social Media','Content Creation'],
                                                   22,
                                                   now() ),( gen_random_uuid(),
                                                             'Kanika',
                                                             '9913238006',
                                                             'volunteer',
                                                             array['Language Translation','Counseling'],
                                                             26,
                                                             now() );