-- Demo Data Set 2: Lost Person & Guidance Scenarios with Authentication
-- Parul University Location: 22.3039° N, 73.1813° E
-- All locations within 1km radius

-- =============================================================================
-- STEP 1: CREATE AUTHENTICATED USERS IN AUTH SYSTEM
-- =============================================================================

-- Create auth users for volunteers (Set 2)
insert into auth.users (
   instance_id,
   id,
   aud,
   role,
   email,
   encrypted_password,
   email_confirmed_at,
   confirmation_token,
   confirmation_sent_at,
   recovery_token,
   recovery_sent_at,
   email_change_token_new,
   email_change,
   email_change_sent_at,
   last_sign_in_at,
   raw_app_meta_data,
   raw_user_meta_data,
   is_super_admin,
   created_at,
   updated_at,
   phone,
   phone_confirmed_at,
   phone_change,
   phone_change_token,
   phone_change_sent_at,
   email_change_token_current,
   email_change_confirm_status,
   banned_until,
   reauthentication_token,
   reauthentication_sent_at,
   is_sso_user,
   deleted_at
) values 
-- Volunteer 1
 ( '00000000-0000-0000-0000-000000000000',
           gen_random_uuid(),
           'authenticated',
           'authenticated',
           'vikram.singh.demo2@example.com',
           crypt(
              'password123',
              gen_salt('bf')
           ),
           now(),
           '',
           now(),
           '',
           now(),
           '',
           '',
           now(),
           now(),
           '{"provider": "email", "providers": ["email"]}',
           '{"name": "Inspector Vikram Singh"}',
           false,
           now(),
           now(),
           '+91-9876543101',
           now(),
           '',
           '',
           now(),
           '',
           0,
           now(),
           '',
           now(),
           false,
           null ),
-- Volunteer 2  
           ( '00000000-0000-0000-0000-000000000000',
                    gen_random_uuid(),
                    'authenticated',
                    'authenticated',
                    'meera.gupta.demo2@example.com',
                    crypt(
                       'password123',
                       gen_salt('bf')
                    ),
                    now(),
                    '',
                    now(),
                    '',
                    now(),
                    '',
                    '',
                    now(),
                    now(),
                    '{"provider": "email", "providers": ["email"]}',
                    '{"name": "Meera Gupta"}',
                    false,
                    now(),
                    now(),
                    '+91-9876543102',
                    now(),
                    '',
                    '',
                    now(),
                    '',
                    0,
                    now(),
                    '',
                    now(),
                    false,
                    null ),
-- Volunteer 3
                    ( '00000000-0000-0000-0000-000000000000',
                             gen_random_uuid(),
                             'authenticated',
                             'authenticated',
                             'ravi.acharya.demo2@example.com',
                             crypt(
                                'password123',
                                gen_salt('bf')
                             ),
                             now(),
                             '',
                             now(),
                             '',
                             now(),
                             '',
                             '',
                             now(),
                             now(),
                             '{"provider": "email", "providers": ["email"]}',
                             '{"name": "Ravi Acharya"}',
                             false,
                             now(),
                             now(),
                             '+91-9876543103',
                             now(),
                             '',
                             '',
                             now(),
                             '',
                             0,
                             now(),
                             '',
                             now(),
                             false,
                             null ),
-- Volunteer 4
                             ( '00000000-0000-0000-0000-000000000000',
                                      gen_random_uuid(),
                                      'authenticated',
                                      'authenticated',
                                      'sita.devi.demo2@example.com',
                                      crypt(
                                         'password123',
                                         gen_salt('bf')
                                      ),
                                      now(),
                                      '',
                                      now(),
                                      '',
                                      now(),
                                      '',
                                      '',
                                      now(),
                                      now(),
                                      '{"provider": "email", "providers": ["email"]}',
                                      '{"name": "Sita Devi"}',
                                      false,
                                      now(),
                                      now(),
                                      '+91-9876543104',
                                      now(),
                                      '',
                                      '',
                                      now(),
                                      '',
                                      0,
                                      now(),
                                      '',
                                      now(),
                                      false,
                                      null );

-- Create auth users for pilgrims (Set 2)
insert into auth.users (
   instance_id,
   id,
   aud,
   role,
   email,
   encrypted_password,
   email_confirmed_at,
   confirmation_token,
   confirmation_sent_at,
   recovery_token,
   recovery_sent_at,
   email_change_token_new,
   email_change,
   email_change_sent_at,
   last_sign_in_at,
   raw_app_meta_data,
   raw_user_meta_data,
   is_super_admin,
   created_at,
   updated_at,
   phone,
   phone_confirmed_at,
   phone_change,
   phone_change_token,
   phone_change_sent_at,
   email_change_token_current,
   email_change_confirm_status,
   banned_until,
   reauthentication_token,
   reauthentication_sent_at,
   is_sso_user,
   deleted_at
) values ( '00000000-0000-0000-0000-000000000000',
           gen_random_uuid(),
           'authenticated',
           'authenticated',
           'bharat.mehta.demo2@example.com',
           crypt(
              'password123',
              gen_salt('bf')
           ),
           now(),
           '',
           now(),
           '',
           now(),
           '',
           '',
           now(),
           now(),
           '{"provider": "email", "providers": ["email"]}',
           '{"name": "Bharat Mehta"}',
           false,
           now(),
           now(),
           '+91-9876540101',
           now(),
           '',
           '',
           now(),
           '',
           0,
           now(),
           '',
           now(),
           false,
           null ),( '00000000-0000-0000-0000-000000000000',
                    gen_random_uuid(),
                    'authenticated',
                    'authenticated',
                    'lata.chandra.demo2@example.com',
                    crypt(
                       'password123',
                       gen_salt('bf')
                    ),
                    now(),
                    '',
                    now(),
                    '',
                    now(),
                    '',
                    '',
                    now(),
                    now(),
                    '{"provider": "email", "providers": ["email"]}',
                    '{"name": "Lata Chandra"}',
                    false,
                    now(),
                    now(),
                    '+91-9876540102',
                    now(),
                    '',
                    '',
                    now(),
                    '',
                    0,
                    now(),
                    '',
                    now(),
                    false,
                    null ),( '00000000-0000-0000-0000-000000000000',
                             gen_random_uuid(),
                             'authenticated',
                             'authenticated',
                             'omprakash.yadav.demo2@example.com',
                             crypt(
                                'password123',
                                gen_salt('bf')
                             ),
                             now(),
                             '',
                             now(),
                             '',
                             now(),
                             '',
                             '',
                             now(),
                             now(),
                             '{"provider": "email", "providers": ["email"]}',
                             '{"name": "Omprakash Yadav"}',
                             false,
                             now(),
                             now(),
                             '+91-9876540103',
                             now(),
                             '',
                             '',
                             now(),
                             '',
                             0,
                             now(),
                             '',
                             now(),
                             false,
                             null ),( '00000000-0000-0000-0000-000000000000',
                                      gen_random_uuid(),
                                      'authenticated',
                                      'authenticated',
                                      'pushpa.kumari.demo2@example.com',
                                      crypt(
                                         'password123',
                                         gen_salt('bf')
                                      ),
                                      now(),
                                      '',
                                      now(),
                                      '',
                                      now(),
                                      '',
                                      '',
                                      now(),
                                      now(),
                                      '{"provider": "email", "providers": ["email"]}',
                                      '{"name": "Pushpa Kumari"}',
                                      false,
                                      now(),
                                      now(),
                                      '+91-9876540104',
                                      now(),
                                      '',
                                      '',
                                      now(),
                                      '',
                                      0,
                                      now(),
                                      '',
                                      now(),
                                      false,
                                      null ),( '00000000-0000-0000-0000-000000000000',
                                               gen_random_uuid(),
                                               'authenticated',
                                               'authenticated',
                                               'jagdish.prasad.demo2@example.com',
                                               crypt(
                                                  'password123',
                                                  gen_salt('bf')
                                               ),
                                               now(),
                                               '',
                                               now(),
                                               '',
                                               now(),
                                               '',
                                               '',
                                               now(),
                                               now(),
                                               '{"provider": "email", "providers": ["email"]}',
                                               '{"name": "Jagdish Prasad"}',
                                               false,
                                               now(),
                                               now(),
                                               '+91-9876540105',
                                               now(),
                                               '',
                                               '',
                                               now(),
                                               '',
                                               0,
                                               now(),
                                               '',
                                               now(),
                                               false,
                                               null ),( '00000000-0000-0000-0000-000000000000',
                                                        gen_random_uuid(),
                                                        'authenticated',
                                                        'authenticated',
                                                        'manju.devi.demo2@example.com',
                                                        crypt(
                                                           'password123',
                                                           gen_salt('bf')
                                                        ),
                                                        now(),
                                                        '',
                                                        now(),
                                                        '',
                                                        now(),
                                                        '',
                                                        '',
                                                        now(),
                                                        now(),
                                                        '{"provider": "email", "providers": ["email"]}',
                                                        '{"name": "Manju Devi"}',
                                                        false,
                                                        now(),
                                                        now(),
                                                        '+91-9876540106',
                                                        now(),
                                                        '',
                                                        '',
                                                        now(),
                                                        '',
                                                        0,
                                                        now(),
                                                        '',
                                                        now(),
                                                        false,
                                                        null ),( '00000000-0000-0000-0000-000000000000',
                                                                 gen_random_uuid(),
                                                                 'authenticated',
                                                                 'authenticated',
                                                                 'vinod.kumar.demo2@example.com',
                                                                 crypt(
                                                                    'password123',
                                                                    gen_salt('bf')
                                                                 ),
                                                                 now(),
                                                                 '',
                                                                 now(),
                                                                 '',
                                                                 now(),
                                                                 '',
                                                                 '',
                                                                 now(),
                                                                 now(),
                                                                 '{"provider": "email", "providers": ["email"]}',
                                                                 '{"name": "Vinod Kumar"}',
                                                                 false,
                                                                 now(),
                                                                 now(),
                                                                 '+91-9876540107',
                                                                 now(),
                                                                 '',
                                                                 '',
                                                                 now(),
                                                                 '',
                                                                 0,
                                                                 now(),
                                                                 '',
                                                                 now(),
                                                                 false,
                                                                 null ),( '00000000-0000-0000-0000-000000000000',
                                                                          gen_random_uuid(),
                                                                          'authenticated',
                                                                          'authenticated',
                                                                          'sarita.joshi.demo2@example.com',
                                                                          crypt(
                                                                             'password123',
                                                                             gen_salt('bf')
                                                                          ),
                                                                          now(),
                                                                          '',
                                                                          now(),
                                                                          '',
                                                                          now(),
                                                                          '',
                                                                          '',
                                                                          now(),
                                                                          now(),
                                                                          '{"provider": "email", "providers": ["email"]}',
                                                                          '{"name": "Sarita Joshi"}',
                                                                          false,
                                                                          now(),
                                                                          now(),
                                                                          '+91-9876540108',
                                                                          now(),
                                                                          '',
                                                                          '',
                                                                          now(),
                                                                          '',
                                                                          0,
                                                                          now(),
                                                                          '',
                                                                          now(),
                                                                          false,
                                                                          null ),( '00000000-0000-0000-0000-000000000000',
                                                                                   gen_random_uuid(),
                                                                                   'authenticated',
                                                                                   'authenticated',
                                                                                   'mahesh.tiwari.demo2@example.com',
                                                                                   crypt(
                                                                                      'password123',
                                                                                      gen_salt('bf')
                                                                                   ),
                                                                                   now(),
                                                                                   '',
                                                                                   now(),
                                                                                   '',
                                                                                   now(),
                                                                                   '',
                                                                                   '',
                                                                                   now(),
                                                                                   now(),
                                                                                   '{"provider": "email", "providers": ["email"]}'
                                                                                   ,
                                                                                   '{"name": "Mahesh Tiwari"}',
                                                                                   false,
                                                                                   now(),
                                                                                   now(),
                                                                                   '+91-9876540109',
                                                                                   now(),
                                                                                   '',
                                                                                   '',
                                                                                   now(),
                                                                                   '',
                                                                                   0,
                                                                                   now(),
                                                                                   '',
                                                                                   now(),
                                                                                   false,
                                                                                   null ),( '00000000-0000-0000-0000-000000000000'
                                                                                   ,
                                                                                            gen_random_uuid(),
                                                                                            'authenticated',
                                                                                            'authenticated',
                                                                                            'radha.agrawal.demo2@example.com'
                                                                                            ,
                                                                                            crypt(
                                                                                               'password123',
                                                                                               gen_salt('bf')
                                                                                            ),
                                                                                            now(),
                                                                                            '',
                                                                                            now(),
                                                                                            '',
                                                                                            now(),
                                                                                            '',
                                                                                            '',
                                                                                            now(),
                                                                                            now(),
                                                                                            '{"provider": "email", "providers": ["email"]}'
                                                                                            ,
                                                                                            '{"name": "Radha Agrawal"}',
                                                                                            false,
                                                                                            now(),
                                                                                            now(),
                                                                                            '+91-9876540110',
                                                                                            now(),
                                                                                            '',
                                                                                            '',
                                                                                            now(),
                                                                                            '',
                                                                                            0,
                                                                                            now(),
                                                                                            '',
                                                                                            now(),
                                                                                            false,
                                                                                            null );

-- =============================================================================
-- STEP 2: CREATE PROFILES LINKED TO AUTH USERS
-- =============================================================================

-- Create Demo Volunteers (Set 2) - Now linked to auth users
insert into profiles (
   id,
   name,
   email,
   phone,
   role,
   is_active,
   volunteer_status,
   skills,
   created_at,
   updated_at
)
   select au.id,
          json_value(au.raw_user_meta_data,
                     '$.name'),
          au.email,
          au.phone,
          'volunteer',
          true,
          case
             when au.email like '%ravi.acharya%' then
                'busy'
             else
                'available'
          end,
          case
             when au.email like '%vikram.singh%' then
                array['lost_person',
                'emergency','crowd_management']
             when au.email like '%meera.gupta%' then
                array['guidance',
                'lost_person','sanitation']
             when au.email like '%ravi.acharya%' then
                array['guidance',
                'crowd_management','emergency']
             when au.email like '%sita.devi%' then
                array['guidance',
                'medical','lost_person']
          end,
          now(),
          now()
     from auth.users au
    where au.email in ( 'vikram.singh.demo2@example.com',
                        'meera.gupta.demo2@example.com',
                        'ravi.acharya.demo2@example.com',
                        'sita.devi.demo2@example.com' );

-- Continue with rest of demo-data-set-2.sql (this file needs full authentication update)
-- This file still uses old schema format and needs to be updated like demo-data-set-2-auth.sql

-- NOTE: This file is outdated and should be replaced with the authenticated version
-- Use demo-data-set-2-auth.sql instead, or copy its structure to this file

-- Current issues in this file:
-- 1. Uses hardcoded IDs instead of proper auth.users integration
-- 2. Uses old schema column names (request_type, urgency_level, location_lat/lng)
-- 3. No authentication setup
-- 4. IDs are text strings instead of UUIDs

-- For immediate use, refer to demo-data-set-2-auth.sql which has:
-- ✅ Proper Supabase authentication
-- ✅ Correct schema column names  
-- ✅ UUID generation for IDs
-- ✅ PostGIS geography format for locations
-- ✅ Complete cleanup scripts

-- Create Assistance Requests (Set 2) - Lost Person & Guidance Focus
insert into assistance_requests (
   id,
   user_id,
   request_type,
   description,
   urgency_level,
   status,
   location_lat,
   location_lng,
   location_description,
   created_at,
   updated_at
) values ( 'demo-request-2-001',
           'demo-pilgrim-2-001',
           'lost_person',
           'My wife got separated in the crowd 30 minutes ago. She is 65 years old, wearing white saree.',
           'high',
           'pending',
           22.3042,
           73.1817,
           'Near University Main Auditorium',
           now(),
           now() ),( 'demo-request-2-002',
                     'demo-pilgrim-2-002',
                     'guidance',
                     'First time visiting. Need help finding the registration desk for senior citizens.',
                     'low',
                     'pending',
                     22.3038,
                     73.1813,
                     'University Entrance Plaza',
                     now(),
                     now() ),( 'demo-request-2-003',
                               'demo-pilgrim-2-003',
                               'lost_person',
                               'Lost my teenage daughter (16 years) in the crowd. She has long black hair, wearing pink kurta.'
                               ,
                               'high',
                               'pending',
                               22.3044,
                               73.1819,
                               'Near University Sports Complex',
                               now(),
                               now() ),( 'demo-request-2-004',
                                         'demo-pilgrim-2-004',
                                         'guidance',
                                         'Cannot find wheelchair accessible restroom facilities. Urgent need for disabled person.'
                                         ,
                                         'medium',
                                         'pending',
                                         22.3036,
                                         73.1808,
                                         'University Administration Block',
                                         now(),
                                         now() ),( 'demo-request-2-005',
                                                   'demo-pilgrim-2-005',
                                                   'lost_person',
                                                   'My elderly father (80 years) wandered off. He has memory issues and may be confused.'
                                                   ,
                                                   'high',
                                                   'pending',
                                                   22.3048,
                                                   73.1824,
                                                   'University Garden Area',
                                                   now(),
                                                   now() ),( 'demo-request-2-006',
                                                             'demo-pilgrim-2-006',
                                                             'guidance',
                                                             'Need directions to special needs assistance center. Carrying disabled child.'
                                                             ,
                                                             'medium',
                                                             'pending',
                                                             22.3030,
                                                             73.1811,
                                                             'University Parking Lot D',
                                                             now(),
                                                             now() ),( 'demo-request-2-007',
                                                                       'demo-pilgrim-2-007',
                                                                       'lost_person',
                                                                       'Missing person: 45-year-old man with walking stick, wearing yellow shirt. Last seen 1 hour ago.'
                                                                       ,
                                                                       'medium',
                                                                       'pending',
                                                                       22.3050,
                                                                       73.1815,
                                                                       'University Central Lawn',
                                                                       now(),
                                                                       now() ),( 'demo-request-2-008',
                                                                                 'demo-pilgrim-2-008',
                                                                                 'guidance',
                                                                                 'Looking for lost and found office. Lost important documents and mobile phone.'
                                                                                 ,
                                                                                 'low',
                                                                                 'pending',
                                                                                 22.3032,
                                                                                 73.1806,
                                                                                 'University Library Building',
                                                                                 now(),
                                                                                 now() ),( 'demo-request-2-009',
                                                                                           'demo-pilgrim-2-009',
                                                                                           'guidance',
                                                                                           'Need help finding bus stop for return journey to Ahmedabad. Have heavy luggage.'
                                                                                           ,
                                                                                           'low',
                                                                                           'pending',
                                                                                           22.3046,
                                                                                           73.1821,
                                                                                           'University Transport Hub',
                                                                                           now(),
                                                                                           now() ),( 'demo-request-2-010',
                                                                                                     'demo-pilgrim-2-010',
                                                                                                     'lost_person',
                                                                                                     'My 12-year-old grandson is missing for 45 minutes. He was playing near the fountain.'
                                                                                                     ,
                                                                                                     'high',
                                                                                                     'pending',
                                                                                                     22.3041,
                                                                                                     73.1812,
                                                                                                     'University Central Fountain'
                                                                                                     ,
                                                                                                     now(),
                                                                                                     now() );

-- Update User Locations Table
insert into user_locations (
   user_id,
   latitude,
   longitude,
   accuracy,
   timestamp,
   is_active
) values ( 'demo-volunteer-2-001',
           22.3040,
           73.1816,
           10.0,
           now(),
           true ),( 'demo-volunteer-2-002',
                    22.3046,
                    73.1811,
                    10.0,
                    now(),
                    true ),( 'demo-volunteer-2-003',
                             22.3034,
                             73.1822,
                             10.0,
                             now(),
                             true ),( 'demo-volunteer-2-004',
                                      22.3052,
                                      73.1809,
                                      10.0,
                                      now(),
                                      true ),( 'demo-pilgrim-2-001',
                                               22.3042,
                                               73.1817,
                                               10.0,
                                               now(),
                                               true ),( 'demo-pilgrim-2-002',
                                                        22.3038,
                                                        73.1813,
                                                        10.0,
                                                        now(),
                                                        true ),( 'demo-pilgrim-2-003',
                                                                 22.3044,
                                                                 73.1819,
                                                                 10.0,
                                                                 now(),
                                                                 true ),( 'demo-pilgrim-2-004',
                                                                          22.3036,
                                                                          73.1808,
                                                                          10.0,
                                                                          now(),
                                                                          true ),( 'demo-pilgrim-2-005',
                                                                                   22.3048,
                                                                                   73.1824,
                                                                                   10.0,
                                                                                   now(),
                                                                                   true ),( 'demo-pilgrim-2-006',
                                                                                            22.3030,
                                                                                            73.1811,
                                                                                            10.0,
                                                                                            now(),
                                                                                            true ),( 'demo-pilgrim-2-007',
                                                                                                     22.3050,
                                                                                                     73.1815,
                                                                                                     10.0,
                                                                                                     now(),
                                                                                                     true ),( 'demo-pilgrim-2-008'
                                                                                                     ,
                                                                                                              22.3032,
                                                                                                              73.1806,
                                                                                                              10.0,
                                                                                                              now(),
                                                                                                              true ),( 'demo-pilgrim-2-009'
                                                                                                              ,
                                                                                                                       22.3046
                                                                                                                       ,
                                                                                                                       73.1821
                                                                                                                       ,
                                                                                                                       10.0,
                                                                                                                       now(),
                                                                                                                       true )
                                                                                                                       ,( 'demo-pilgrim-2-010'
                                                                                                                       ,
                                                                                                                            22.3041
                                                                                                                            ,
                                                                                                                            73.1812
                                                                                                                            ,
                                                                                                                            10.0
                                                                                                                            ,
                                                                                                                            now
                                                                                                                            (
                                                                                                                            )
                                                                                                                            ,
                                                                                                                            true
                                                                                                                            )
                                                                                                                            ;

/*
-- CLEANUP SCRIPT FOR DEMO DATA SET 2
-- Run this to completely remove all demo data from this set

-- Delete assistance requests first (due to foreign key constraints)
DELETE FROM assistance_requests WHERE id LIKE 'demo-request-2-%';

-- Delete user locations
DELETE FROM user_locations WHERE user_id LIKE 'demo-volunteer-2-%' OR user_id LIKE 'demo-pilgrim-2-%';

-- Delete assignments if any exist
DELETE FROM assignments WHERE volunteer_id LIKE 'demo-volunteer-2-%' OR request_id LIKE 'demo-request-2-%';

-- Delete profiles
DELETE FROM profiles WHERE id LIKE 'demo-volunteer-2-%' OR id LIKE 'demo-pilgrim-2-%';

-- Verify cleanup
SELECT COUNT(*) as remaining_demo_profiles FROM profiles WHERE id LIKE 'demo-volunteer-2-%' OR id LIKE 'demo-pilgrim-2-%';
SELECT COUNT(*) as remaining_demo_requests FROM assistance_requests WHERE id LIKE 'demo-request-2-%';
SELECT COUNT(*) as remaining_demo_locations FROM user_locations WHERE user_id LIKE 'demo-volunteer-2-%' OR user_id LIKE 'demo-pilgrim-2-%';
*/